apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-genai-knowledge-base
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Generative AI Knowledge Base
    source:
      repo: https://github.com/GoogleCloudPlatform/terraform-genai-knowledge-base.git
      sourceType: git
    version: 0.1.1
    actuationTool:
      flavor: Terraform
      version: ">= 0.13"
    description:
      tagline: Fine tune an LLM model to answer questions from your documents.
      detailed: |-
        This solution showcases how to extract question & answer pairs out of documents
        using Generative AI. It provides an end-to-end demonstration of QA extraction and
        fine-tuning of a large language model (LLM) on Vertex AI. Along the way, the
        solution utilizes Document AI Character Recognition (OCR), Firestore,
        Vertex AI Studio, and Cloud Functions.
      preDeploy: To deploy this blueprint you must have an active billing account and billing permissions.
    icon: assets/icon.png
    deploymentDuration:
      configurationSecs: 120
      deploymentSecs: 480
    costEstimate:
      description: Cost Details
      url: https://cloud.google.com/products/calculator-legacy#id=94ab5d75-4134-410f-b2d0-350762ae2588
    cloudProducts:
      - productId: ai-platform
        label: Vertex AI
      - productId: document-ai
        label: Document AI OCR
      - productId: FIRESTORE_SECTION
        label: Firestore
      - productId: FUNCTIONS_SECTION
        label: Cloud Functions
      - productId: STORAGE_SECTION
        label: Cloud Storage
  content:
    architecture:
      diagramUrl: architecture-diagram.url
      description:
        - Uploading a new document triggers the webhook Cloud Function
        - Document AI extracts the text from the document file
        - A Vertex AI Large Language Model generates questions and answers from the document text
        - The questions and answers pairs are saved into Firestore
        - A fine tuning dataset is generated from the Firestore database
        - After human validation, a fine tuned Large Language Model is deployed and saved in the Model Registry
    documentation:
      - title: Knowledge Base using Generative AI
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: delete_contents_on_destroy
        description: Whether to delete resource contents on destroy.
        varType: bool
        defaultValue: true
      - name: disable_services_on_destroy
        description: Whether project services will be disabled when the resources are destroyed.
        varType: bool
        defaultValue: false
      - name: documentai_location
        description: Document AI location, see https://cloud.google.com/document-ai/docs/regions
        varType: string
        defaultValue: us
      - name: firestore_location
        description: Firestore location, see https://firebase.google.com/docs/firestore/locations
        varType: string
        defaultValue: nam5
      - name: labels
        description: A map of key/value label pairs to assign to the resources.
        varType: map(string)
        defaultValue:
          app: genai-knowledge-base
      - name: project_id
        description: The Google Cloud project ID to deploy to
        varType: string
        defaultValue: null
        required: true
      - name: region
        description: The Google Cloud region to deploy to
        varType: string
        defaultValue: us-central1
      - name: unique_names
        description: Whether to use unique names for resources
        varType: bool
        defaultValue: false
      - name: webhook_path
        description: Path to the webhook source directory
        varType: string
        defaultValue: webhook
    outputs:
      - name: bucket_docs_name
        description: The name of the docs bucket created
      - name: bucket_main_name
        description: The name of the main bucket created
      - name: docs_index_endpoint_id
        description: The ID of the docs index endpoint
      - name: docs_index_id
        description: The ID of the docs index
      - name: documentai_processor_id
        description: The full Document AI processor path ID
      - name: firestore_database_name
        description: The name of the Firestore database created
      - name: neos_walkthrough_url
        description: The URL to launch the in-console tutorial for the Generative AI Knowledge Base solution
      - name: unique_id
        description: The unique ID for this deployment
  requirements:
    roles:
      - level: Project
        roles:
          - roles/aiplatform.user
          - roles/documentai.editor
          - roles/firebase.admin
          - roles/iam.serviceAccountUser
    services:
      - aiplatform.googleapis.com
      - artifactregistry.googleapis.com
      - cloudbuild.googleapis.com
      - cloudfunctions.googleapis.com
      - documentai.googleapis.com
      - eventarc.googleapis.com
      - firestore.googleapis.com
      - run.googleapis.com
      - storage.googleapis.com
